name: Build and Publish Docker Images

# 1. THE TRIGGER: When should the robot wake up?
on:
  push:
    branches: ['main'] # Only run when code is merged into main

# 2. THE PERMISSIONS: Give the robot keys to upload to GHCR
permissions:
  contents: read
  packages: write

jobs:
  push-to-registry:
    runs-on: ubuntu-latest # The virtual computer type
    
    steps:
        # Pull your code into the virtual computer
      - name: Checkout repository
        uses: actions/checkout@v4

        # Log into GitHub Container Registry (GHCR)
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/mahammadakhil/build-animated-cicd-website
          tags: |
            type=raw,value=latest
            type=raw,value=main
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
